from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home, name="home"),
    path('compra.html', views.compra, name="compra"),
    path('eliminar1', views.eliminar1, name="eliminar1"),
    path('flores1', views.flores1, name="flores1"),
    path('flores2', views.flores2, name="flores2"),
    path('flores3', views.flores3, name="flores3"),
    path('flores4', views.flores4, name="flores4"),
    path('flores5', views.flores5, name="flores5"),
    path('flores6', views.flores6, name="flores6"),
    path('sesion', LoginView.as_view(template_name='core/iniciosesion.html'), name="sesion"),
    path('mace1', views.mace1, name="mace1"),
    path('mace2', views.mace2, name="mace2"),
    path('mace3', views.mace3, name="mace3"),
    path('mace4', views.mace4, name="mace4"),
    path('mace5', views.mace5, name="mace5"),
    path('maceteros', views.maceteros, name="maceteros"),
    path('miscompras', views.miscompras, name="miscompras"),
    path('nosotros', views.nosotros, name="nosotros"),
    path('plantas', views.plantas, name="plantas"),
    path('registro', views.registro, name="registro"),
    path('sus', views.sus, name="sus"),
    path('suscripcion', views.suscripcion, name="suscripcion"),
    path('tierra', views.tierra, name="tierra"),
    path('tierra1', views.tierra1, name="tierra1"),
    path('tierra2', views.tierra2, name="tierra2"),
    path('tierra3', views.tierra3, name="tierra3"),
    path('tablaproducto', views.tablaProducto, name="tablaProducto"),
    path('modificar/<id>', views.modificar, name="modificar"),
    path('crear', views.crear, name="crear"),
    path('eliminar/<id>', views.eliminar, name="eliminar"),
    path('logout', LogoutView.as_view(template_name='core/logout.html'), name="logout"),
    path('tablapromo', views.tablaPromo, name="tablaPromo"),
    path('crearPromo', views.crear1, name="crear1"),
    path('modificarPromo/<id>', views.modificarPromo, name="modificarPromo"),
    path('eliminar2/<id>', views.eliminar2, name="eliminar2"),
    path('des', views.des, name="des"),
    path('susc', views.susc, name="susc"),
]