# Generated by Django 3.2.4 on 2022-07-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idPromocion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePromocion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('producto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('descuento', models.IntegerField()),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion')),
            ],
        ),
    ]
