# Generated by Django 3.2.4 on 2022-07-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_descuentos_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='producto',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
